addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.10.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js"       % "sbt-jsdependencies"       % "1.0.2")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"          % "1.2.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-web-scalajs-bundler"  % "0.21.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-digest"               % "1.1.4")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.9.1")
